// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnmZvIwtmhvZ5N897HZO48QKNwjF9oFdw',
    appId: '1:932867187299:web:ebad6528141e6787040e56',
    messagingSenderId: '932867187299',
    projectId: 'storish-codecamp',
    authDomain: 'storish-codecamp.firebaseapp.com',
    storageBucket: 'storish-codecamp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ_9r6cwxJwVL1y-WQAVeSHF6P8ZLOVAE',
    appId: '1:932867187299:android:a7d17f36f8c9014f040e56',
    messagingSenderId: '932867187299',
    projectId: 'storish-codecamp',
    storageBucket: 'storish-codecamp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmVBJNJCmuRX4WwGt4S-0tXT_rdn-u-1U',
    appId: '1:932867187299:ios:7d3b8ddc88793330040e56',
    messagingSenderId: '932867187299',
    projectId: 'storish-codecamp',
    storageBucket: 'storish-codecamp.appspot.com',
    iosClientId: '932867187299-0s604hdeu50k2k3k8m3mf1hdn0u0kt5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.storish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmVBJNJCmuRX4WwGt4S-0tXT_rdn-u-1U',
    appId: '1:932867187299:ios:7d3b8ddc88793330040e56',
    messagingSenderId: '932867187299',
    projectId: 'storish-codecamp',
    storageBucket: 'storish-codecamp.appspot.com',
    iosClientId: '932867187299-0s604hdeu50k2k3k8m3mf1hdn0u0kt5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.storish',
  );
}
